version: '3'
services:
  neo4j:
    image: neo4j:3.3.0-enterprise
    ports:
      - "7474:7474"
      - "7687:7687" 
    volumes:
      - ./plugins:/plugins
      - ./conf:/conf
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes